#!/bin/bash
clang-format -i $(find "$PWD/src/" -regextype posix-extended -iregex ".*/src/.*\.(c|cpp|cxx|h|hpp)$")
clang-format -i $(find "$PWD/include/" -regextype posix-extended -iregex ".*/include/.*\.(h|hpp)$")
